name = "Modpack Bog"
author = "Casmin7"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "130d13ccdff6b718f5a4ba89f25875f8562f5a4cfce66faf79fceaf578bde3e9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
