name = "Modpack Bog"
author = "Casmin7"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31f771b512e73f641b4cc74ed11c57851ba34b6d96587d1111a38b23975cefe4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
