name = "Modpack Bog"
author = "Casmin7"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38e9a7ad3b83831987f1045c44cdfe3d9b1f1f86855d8704a60ebe2cf0e2576f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
