#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 30 19:59:07 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
