#.
#Parameters of Simurail block behaviors
[blocks]

	#.
	#.
	#Connections
	[blocks.connection]
		#.
		#[in ṁ]
		#The maximum distance of connections between Physics Bogeys on the same sublevel.
		# Default: 32.0
		# Range: 1.0 ~ 256.0
		bogeyRangeSame = 32.0
		#.
		#[in ṁ]
		#The maximum distance of connections between Physics Bogeys on different sublevels.
		# Default: 12.0
		# Range: 1.0 ~ 256.0
		bogeyRangeDifferent = 12.0
		#.
		#[in ṁ]
		#The maximum distance of connections between a Train Coupler and a Physics Bogey.
		# Default: 4.0
		# Range: 1.0 ~ 256.0
		couplerRange = 4.0

#.
#Parameters of Simurail physics behaviors
[physics]

	#.
	#.
	#Physics Bogies
	[physics.bogey]
		#.
		#[in kġ]
		#The mass of the pivot of the Physics Bogey.
		# Default: 1.0
		# Range: 0.0 ~ 3.4028234663852886E38
		pivotMass = 1.0

		#.
		#Vertical Movement
		[physics.bogey.vertical]
			#.
			#[in rad/s]
			#Vertical spring frequency between the Physics Bogey and its pivot when vertical offset is allowed.
			# Default: 10.0
			# Range: 0.0 ~ 3.4028234663852886E38
			springFrequency = 10.0
			#.
			#Vertical spring damping rate between the Physics Bogey and its pivot when vertical offset is allowed.
			# Default: 1.25
			# Range: 0.0 ~ 3.4028234663852886E38
			springDampingRate = 1.25
			#.
			#[in Ṅ]
			#Vertical spring maximum force between the Physics Bogey and its pivot when vertical offset is allowed.
			# Default: 10000.0
			# Range: 0.0 ~ 3.4028234663852886E38
			springMaxForce = 10000.0
			#.
			#[in rad/s]
			#Vertical locking spring frequency between the Physics Bogey and its pivot when rotation offset is disallowed.
			# Default: 10.0
			# Range: 0.0 ~ 3.4028234663852886E38
			lockingSpringFrequency = 10.0
			#.
			#Vertical locking spring damping rate between the Physics Bogey and its pivot when rotation offset is disallowed.
			# Default: 1.5
			# Range: 0.0 ~ 3.4028234663852886E38
			lockingSpringDampingRate = 1.5

		#.
		#Lateral Movement
		[physics.bogey.lateral]
			#.
			#[in rad/s]
			#Lateral spring frequency between the Physics Bogey and its pivot when lateral offset is allowed.
			# Default: 10.0
			# Range: 0.0 ~ 3.4028234663852886E38
			springFrequency = 10.0
			#.
			#Lateral spring damping rate between the Physics Bogey and its pivot when lateral offset is allowed.
			# Default: 1.25
			# Range: 0.0 ~ 3.4028234663852886E38
			springDampingRate = 1.25
			#.
			#[in Ṅ]
			#Lateral spring maximum force between the Physics Bogey and its pivot when lateral offset is allowed.
			# Default: 10000.0
			# Range: 0.0 ~ 3.4028234663852886E38
			springMaxForce = 10000.0
			#.
			#[in rad/s]
			#Lateral locking spring frequency between the Physics Bogey and its pivot when rotation offset is disallowed.
			# Default: 10.0
			# Range: 0.0 ~ 3.4028234663852886E38
			lockingSpringFrequency = 10.0
			#.
			#Lateral locking spring damping rate between the Physics Bogey and its pivot when rotation offset is disallowed.
			# Default: 1.5
			# Range: 0.0 ~ 3.4028234663852886E38
			lockingSpringDampingRate = 1.5

		#.
		#Roll Movement
		[physics.bogey.roll]
			#.
			#[in rad/s]
			#Roll spring frequency between the Physics Bogey and its pivot.
			# Default: 15.0
			# Range: 0.0 ~ 3.4028234663852886E38
			springFrequency = 15.0
			#.
			#Roll spring damping rate between the Physics Bogey and its pivot.
			# Default: 1.25
			# Range: 0.0 ~ 3.4028234663852886E38
			springDampingRate = 1.25
			#.
			#Roll spring moment multiplier between the Physics Bogey and its pivot.
			# Default: 2.0
			# Range: 0.0 ~ 3.4028234663852886E38
			springMomentMultiplier = 2.0
			#.
			#[in Ṅ∙ṁ]
			#Roll spring maximum torque between the Physics Bogey and its pivot.
			# Default: 10000.0
			# Range: 0.0 ~ 3.4028234663852886E38
			springMaxTorque = 10000.0

		#.
		#Yaw Movement
		[physics.bogey.yaw]
			#.
			#[in rad/s]
			#Yaw locking spring frequency between the Physics Bogey and its pivot when yaw offset is disallowed.
			# Default: 50.0
			# Range: 0.0 ~ 3.4028234663852886E38
			lockingSpringFrequency = 50.0
			#.
			#Yaw locking spring damping rate between the Physics Bogey and its pivot when yaw offset is disallowed.
			# Default: 1.5
			# Range: 0.0 ~ 3.4028234663852886E38
			lockingSpringDampingRate = 1.5

		#.
		#Pitch Movement
		[physics.bogey.pitch]
			#.
			#[in rad/s]
			#Pitch locking spring frequency between the Physics Bogey and its pivot when pitch offset is disallowed.
			# Default: 50.0
			# Range: 0.0 ~ 3.4028234663852886E38
			lockingSpringFrequency = 50.0
			#.
			#Pitch locking spring damping rate between the Physics Bogey and its pivot when pitch offset is disallowed.
			# Default: 1.5
			# Range: 0.0 ~ 3.4028234663852886E38
			lockingSpringDampingRate = 1.5

	#.
	#Physics Bogie Axles
	[physics.axle]
		#.
		#[in s]
		#Time to update the axle spacing when changed for the axles of the Physics Bogey.
		# Default: 2.0
		# Range: 0.0 ~ 10.0
		spacingUpdateTime = 2.0
		#.
		#[in Ṅ∙s/ṁ]
		#Passive linear damping between an axle of the Physics Bogey and its track.
		# Default: 100.0
		# Range: 0.0 ~ 3.4028234663852886E38
		passiveLinearDamping = 100.0
		#.
		#[in Ṅ∙ṁ∙s/rad]
		#Passive angular damping between an axle of the Physics Bogey and its track.
		# Default: 1.0
		# Range: 0.0 ~ 3.4028234663852886E38
		passiveAngularDamping = 1.0
		#.
		#[in ṁ/s²]
		#Lateral max speed factor between an axle of the Physics Bogey and a standard track. Max speed is sqrt(factor / curvature).
		# Default: 30.0
		# Range: 0.0 ~ 3.4028234663852886E38
		standardLateralMaxSpeedFactor = 30.0
		#.
		#[in ṁ/s²]
		#Vertical max speed factor between an axle of the Physics Bogey and a standard track. Max speed is sqrt(factor / curvature).
		# Default: 50.0
		# Range: 0.0 ~ 3.4028234663852886E38
		standardVerticalMaxSpeedFactor = 50.0
		#.
		#[in ṁ/s]
		#Conversion of RPM to target speed between an axle of the Physics Bogey and its track.
		# Default: 0.25
		# Range: 0.0 ~ 3.4028234663852886E38
		targetSpeedFactor = 0.25
		#.
		#[in Ṅ∙s/ṁ]
		#Conversion of current and target speed difference to drive force between an axle of the Physics Bogey and its track.
		# Default: 0.5
		# Range: 0.0 ~ 3.4028234663852886E38
		driveForceFactor = 0.5
		#.
		#[in ṁ/s²]
		#Conversion of brake strength [0-1] to brake force between an axle of the Physics Bogey and its track.
		# Default: 20.0
		# Range: 0.0 ~ 3.4028234663852886E38
		brakeStrengthFactor = 20.0
		#.
		#Factor of effective friction between an axle of the Physics Bogey and the ground when derailed.
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		derailFrictionFactor = 0.5
		#.
		#[in s]
		#Inverval to find nearest track when derailed for an axle of the Physics Bogey.
		# Default: 0.10000000149011612
		# Range: 0.0 ~ 5.0
		trackCheckTime = 0.10000000149011612
		#.
		#[in s]
		#Inverval to re-find nearest track for an axle of the Physics Bogey.
		# Default: 3.0
		# Range: 0.0 ~ 60.0
		trackRecheckTime = 3.0

	#.
	#Train Couplers
	[physics.coupler]
		#.
		#[in Ṅ∙s/ṁ]
		#Passive linear damping between a Train Coupler and its partner.
		# Default: 10.0
		# Range: 0.0 ~ 3.4028234663852886E38
		passiveLinearDamping = 10.0
		#.
		#[in Ṅ∙ṁ∙s/rad]
		#Passive angular damping between a Train Coupler and its partner.
		# Default: 1.0
		# Range: 0.0 ~ 3.4028234663852886E38
		passiveAngularDamping = 1.0
		#.
		#[in rad/s]
		#Spring frequency between a Train Coupler and its partner.
		# Default: 100.0
		# Range: 0.0 ~ 3.4028234663852886E38
		springFrequency = 100.0
		#.
		#Spring damping rate between a Train Coupler and its partner.
		# Default: 2.0
		# Range: 0.0 ~ 3.4028234663852886E38
		springDampingRate = 2.0

#.
#Parameters of Simurail compat behaviors
[compat]

	#.
	#.
	#Steam 'n' Rails
	[compat.railways]
		#.
		#[in ṁ/s²]
		#Lateral max speed factor between an axle of the Physics Bogey and a monorail track. Max speed is sqrt(factor / curvature).
		# Default: 500.0
		# Range: 0.0 ~ 3.4028234663852886E38
		monorailLateralMaxSpeedFactor = 500.0
		#.
		#[in ṁ/s²]
		#Vertical max speed factor between an axle of the Physics Bogey and a monorail track. Max speed is sqrt(factor / curvature).
		# Default: 100.0
		# Range: 0.0 ~ 3.4028234663852886E38
		monorailVerticalMaxSpeedFactor = 100.0
		#.
		#[in ṁ/s²]
		#Lateral max speed factor between an axle of the Physics Bogey and a narrow track. Max speed is sqrt(factor / curvature).
		# Default: 25.0
		# Range: 0.0 ~ 3.4028234663852886E38
		narrowLateralMaxSpeedFactor = 25.0
		#.
		#[in ṁ/s²]
		#Vertical max speed factor between an axle of the Physics Bogey and a narrow track. Max speed is sqrt(factor / curvature).
		# Default: 50.0
		# Range: 0.0 ~ 3.4028234663852886E38
		narrowVerticalMaxSpeedFactor = 50.0
		#.
		#[in ṁ/s²]
		#Lateral max speed factor between an axle of the Physics Bogey and a wide track. Max speed is sqrt(factor / curvature).
		# Default: 50.0
		# Range: 0.0 ~ 3.4028234663852886E38
		wideLateralMaxSpeedFactor = 50.0
		#.
		#[in ṁ/s²]
		#Vertical max speed factor between an axle of the Physics Bogey and a wide track. Max speed is sqrt(factor / curvature).
		# Default: 50.0
		# Range: 0.0 ~ 3.4028234663852886E38
		wideVerticalMaxSpeedFactor = 50.0
